# Wordpress
#
hostname: "www.my.site"

certificate: false
ingress: false

git_host: "github.com"
git_repo: "username/website.git"

provision:
  image: "ghcr.io/gluobe/wordpress-deploy"
  tag: "latest"

imageCredentials: {}
#  registry: ghcr.io
#  username: 
#  password: 
#  email: 

secretProvider: {}

storage:
  code:
    accessModes: "ReadWriteOnce"
    storageClassName: "default"
    resources: 1Gi

nginx:
  image: "nginx"
  tag: "1.17.0"
  replicas: 1

php:
  image: "wordpress"
  tag: "5.7-fpm"
  replicas: 1
  admin:
    firstname: "Web"
    lastname: "Master"
    email: "webmaster@gluo.be"
    username: "webmaster"
    password: "test"

mysql:
  image:
    config:
      username: "wordpress"
      password: "abc123456xyz"
      database: "wp_website"
