---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    component: nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
{{ if eq .Values.ingress true }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
{{ if eq .Values.certificate true }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
{{ end }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-nginx
          servicePort: 80
{{ if eq .Values.certificate true }}
  tls:
  - hosts: 
    - {{ .Values.hostname }}
    secretName: tls-wordpress
{{ end }}
{{ end }}
