---
apiVersion: v1
kind: Service
metadata:
  name: nginx-http
spec:
  selector:
    component: nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
{{ if eq .Values.ingress.enabled true }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
{{ if eq .Values.certificate true }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
{{ end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        backend:
          serviceName: nginx-http
          servicePort: 80
      {{- end }}
  {{- end }}
{{ if eq .Values.certificate true }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts: 
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
{{ end }}
{{ end }}
{{ end }}
