---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
stringData:
  username: {{ .Values.database.config.username }}
  password: {{ .Values.database.config.password }}
{{ if .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-environment
type: Opaque
data:
  auth_key: {{ randAscii 64 | b64enc }}
  secure_auth_key: {{ randAscii 64 | b64enc  }}
  logged_in_key: {{ randAscii 64 | b64enc }}
  nonce_key: {{ randAscii 64 | b64enc }}
  auth_salt: {{ randAscii 64 | b64enc }}
  secure_auth_salt: {{ randAscii 64 | b64enc }}
  logged_in_salt: {{ randAscii 64 | b64enc }}
  nonce_salt: {{ randAscii 64 | b64enc }}
