{{ if .Values.imageCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.registry }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-environment
type: Opaque
data:
  auth_key: {{ randAscii 64 | b64enc }}
  secure_auth_key: {{ randAscii 64 | b64enc  }}
  logged_in_key: {{ randAscii 64 | b64enc }}
  nonce_key: {{ randAscii 64 | b64enc }}
  auth_salt: {{ randAscii 64 | b64enc }}
  secure_auth_salt: {{ randAscii 64 | b64enc }}
  logged_in_salt: {{ randAscii 64 | b64enc }}
  nonce_salt: {{ randAscii 64 | b64enc }}
