---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-code
spec:
  accessModes:
    - {{ .Values.storage.code.accessModes }}
  resources: 
    requests: 
      storage: {{ .Values.storage.code.resources }}
  storageClassName: {{ .Values.storage.code.storageClassName }}
