---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    component: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}

