---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources: 
    requests:
      storage: {{ .Values.storage.resources }}
  storageClassName: {{ .Values.storage.storageClassName }}
